version: '3'

services:
  web:
    image: python:3.12-slim
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=attendance_monitoring_system
      - DB_USER=student_management_system
      - DB_PASSWORD=student_management_password
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - MYSQLCLIENT_CFLAGS=-I/usr/include/mysql
      - MYSQLCLIENT_LDFLAGS=-L/usr/lib/x86_64-linux-gnu -lmysqlclient
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    working_dir: /app
    command: >
      bash -c "apt-get update && 
              apt-get install -y default-libmysqlclient-dev gcc pkg-config && 
              pip install pymysql && 
              pip install -r requirements.txt && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  static_volume:
  media_volume: 